### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [27]:
import numpy as np

def is_prime(n):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False

    i = 3
    while i * i <= n:   
        if n % i == 0:
            return False
        i += 2          # salta i pari
    return True

# 1.
primes = np.array([i for i in range(2,20) if is_prime(i)]) # selezioniamo solo i primi nel range

print("primi:", primes)

# 2.
primes[primes > 10] # selezioniamo solo gli elementi strettamente maggiori di 10

print("primi > 10:", primes[primes>10])

# 3.
primes[primes % 2 == 0] # selezioniamo i primi pari (l'unico è 2)

print("primi pari:", primes[primes % 2 == 0])

primi: [ 2  3  5  7 11 13 17 19]
primi > 10: [11 13 17 19]
primi pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [28]:
a = np.arange(20).reshape((4, 5))

print("a:",a)

b = a[[1, 3]] # selezioniamo seconda e quarta riga (indici 1 e 3)

print("b:",b)

c = a[2,] # selezioniamo solo la terza riga (indice 2)

print("c:",c)

d = a/c

print("a/c:",d)

a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b: [[ 5  6  7  8  9]
 [15 16 17 18 19]]
c: [10 11 12 13 14]
a/c: [[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.5        0.54545455 0.58333333 0.61538462 0.64285714]
 [1.         1.         1.         1.         1.        ]
 [1.5        1.45454545 1.41666667 1.38461538 1.35714286]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [29]:
np.random.seed(0)

a = np.random.rand(10,3)
print("array 10X3:",a)

b = np.abs(a-0.5) #10,3
print(b)

c = np.argmin(b, axis = 1) #10,1
print(c.shape)

val = a[np.arange(a.shape[0]),np.argmin(b,axis=1)]
print("valori più vicini a 0.5 per riga:",val)


array 10X3: [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]]
[[0.0488135  0.21518937 0.10276338]
 [0.04488318 0.0763452  0.14589411]
 [0.06241279 0.391773   0.46366276]
 [0.11655848 0.29172504 0.02889492]
 [0.06804456 0.42559664 0.42896394]
 [0.4128707  0.4797816  0.33261985]
 [0.27815675 0.37001215 0.47861834]
 [0.29915856 0.03852064 0.28052918]
 [0.38172557 0.13992102 0.35664671]
 [0.44466892 0.02184832 0.08533806]]
(10,)
valori più vicini a 0.5 per riga: [0.5488135  0.54488318 0.43758721 0.52889492 0.56804456 0.83261985
 0.77815675 0.46147936 0.63992102 0.52184832]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [30]:
# 1. 
HR = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

# 2. 
minHR = np.min(HR)
print("min:",minHR)

# 3.
maxHR = np.max(HR)
print("MAX:",maxHR)

# 4. 
activityHR = HR>120
print("HR sopra 120:", activityHR)
print(HR[HR>120])

print("percentuale sopra 120:",(len(HR[HR>120])/len(HR))*100,"%")


min: 60
MAX: 164
HR sopra 120: [False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
[160 161 162 161 160 161 162 163 164 163 162]
percentuale sopra 120: 52.38095238095239 %


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [31]:
# 1.
salaries = np.array([50000,105250,55000,89000])
cost = np.sum(salaries)
print("costo totale:",cost)

# 2. 
salaries[1] *= 1.15
print("aumento CEO:",salaries)

# 3.
# il valore risultante è 121037, che non è esatto in quanto stiamo operando con interi
# mentre il valore atteso è un float

# 4. 
salaries = np.array([50000,105250,55000,89000], dtype = "float")
print("salari float:",salaries)
salaries[1] *= 1.15 # aumento
print("salari corretti con aumento CEO:",salaries)

# 5. 
salaries[0] *= 1.20
print("aumento impegata 1:",salaries)

# 6.
salaries[[2,3]] *= 1.10
print("aumenti impiegati 2 e 3:",salaries)

# 7.
final_cost = np.sum(salaries)
cost_increase = final_cost - cost
print("costo totale dell'aumento:",cost_increase)

costo totale: 299250
aumento CEO: [ 50000 121037  55000  89000]
salari float: [ 50000. 105250.  55000.  89000.]
salari corretti con aumento CEO: [ 50000.  121037.5  55000.   89000. ]
aumento impegata 1: [ 60000.  121037.5  55000.   89000. ]
aumenti impiegati 2 e 3: [ 60000.  121037.5  60500.   97900. ]
costo totale dell'aumento: 40187.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [32]:
# 1.
emissioni = np.loadtxt('emissioni.txt', dtype=float)
print("contenuto file emissioni:",emissioni)

# 2.
over_18 = emissioni[emissioni > 18]
n = len(over_18)
M = np.mean(over_18)
print(f"ci sono {n} valori di CO2 sopra 18 T, e il loro valore medio è: {M}")

# 3.
F = sum(over_18)/sum(emissioni)
print("frazione totale di emissione sopra la soglia:",F)


contenuto file emissioni: [13.69  5.85 15.65 14.2  16.99 11.67 18.64  4.79  8.69 15.44 10.69  6.77
  5.72 17.08 11.57 18.12 15.73 10.56  9.98 12.25 18.22 15.8   4.08 15.11
 18.71 15.37  6.83 11.74  6.25  9.74 18.99 18.77  8.53  9.43 13.6  19.41
  6.36  8.11 17.98 11.87 18.38  6.97 12.52  9.22  9.06 11.15 10.93  9.72
 18.64 15.71 15.64  8.64 13.24 16.47 16.73  9.51 16.33 15.77  6.26 17.86
 11.06 11.78 11.17 13.09 13.94 11.97 17.87 14.04 10.42 10.67 16.97  9.57
  7.38  4.95 18.02 18.7   5.92  9.35  6.81  5.85 18.4   4.91 19.69  5.54
 17.82 13.06  9.89  9.48 16.12  9.03 14.52 12.28 11.76 18.42 12.87 17.23
 15.61  4.62 16.37  7.47 18.45  4.69  9.33  5.6  11.61 17.12  8.77  6.41
  9.28 17.02  6.25  7.64  5.1  15.29 10.32  8.97 15.5   9.38 15.64 17.04
  7.48 19.58  6.6   8.65  6.88  9.53 11.68 12.35 17.66 18.23  7.52 13.97
  5.78 11.34  9.16  9.06 11.72 15.68  5.11 18.07 15.76  6.82 19.03 12.1
 20.    7.16 12.56  8.64  8.87 13.46 18.75 16.88 15.58 12.95 18.76 11.88
 17.98 17.34  7.42 16.34  

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [33]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

# 1. 
more_than_12 = survey_matrix[survey_matrix[:,2] >=  12]

print("intervistati con almeno 12 anni di istruzione:",more_than_12)

# 2.
incomes = survey_matrix[survey_matrix[:,2] >= 12][:, 1]

print("reddito degli intervistati con almeno 12 anni di istruzione:",incomes)

# 3.
print("media reddito degli intervistati con almeno 12 anni di istruzione:",np.mean(incomes))


intervistati con almeno 12 anni di istruzione: [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
reddito degli intervistati con almeno 12 anni di istruzione: [52000 63000 58000]
media reddito degli intervistati con almeno 12 anni di istruzione: 57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [34]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

ages_clean = np.array([n for n in ages if n != 999]) # creo nuova lista omettendo i 999
age_max = np.max(ages_clean)

print("età max:",age_max)

età max: 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [35]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]




Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."

In [36]:
import numpy as np
import textwrap # modulo che ho trovato per stampare meglio la storia

chosen_words = np.random.choice(lista_parole, size=5, replace=True)

story = (
    "In epoche passate, viveva una donna saggia che era molto orgogliosa "
    "dell'antico _ che proteggeva. Quando un anziano del villaggio venne "
    "a chiederle consiglio su come garantire al meglio un raccolto "
    "abbondante e le offrì il _ come dono, i suoi occhi si spalancarono "
    "e lei esclamò una sola parola, \"_\". Radunò il villaggio e, per i "
    "successivi 100 giorni, su sua richiesta, gli abitanti cercarono "
    "nella foresta un _. Nel 101° giorno, il bambino più giovane del "
    "villaggio trovò ciò che stavano cercando e tutti corsero dalla donna "
    "saggia per donarglielo. Con un sorriso da un orecchio all’altro, "
    "e cantando canti di festa, la donna saggia guardò i suoi compaesani "
    "e disse: \"Ora è giunto il tempo del banchetto - nessuno rimarrà "
    "mai più senza _.\" Ci fu grande gioia e celebrazione."
)

for parola in chosen_words:
    story = story.replace("_", parola, 1)

print(textwrap.fill(story, width=80)) # utilizzo il modulo textwrap per stampare la storia visibile completamente.
# senza questo modulo tutto il testo verrebbe stampato in una sola riga e non sarebbe tutto visibile

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico
COPERTA che proteggeva. Quando un anziano del villaggio venne a chiederle
consiglio su come garantire al meglio un raccolto abbondante e le offrì il
AGENTE DI POLIZIA come dono, i suoi occhi si spalancarono e lei esclamò una sola
parola, "DEPOSITO". Radunò il villaggio e, per i successivi 100 giorni, su sua
richiesta, gli abitanti cercarono nella foresta un PALLONCINO. Nel 101° giorno,
il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti
corsero dalla donna saggia per donarglielo. Con un sorriso da un orecchio
all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e
disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza
INSEDIAMENTO." Ci fu grande gioia e celebrazione.
